#!/usr/bin/env bash
# script to fix nginx server that won't shut off via daemon manager
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx start
