#!/usr/bin/env bash
# this script takes 4 parameters
if [ $# -lt 3 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/$1
