#!/usr/bin/env bash
# script to install and setup nginx
INSERT_LINE="rewrite ^/redirect_me / permanent;"
CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Holberton School' > /usr/share/nginx/html/index.html

# update config file to redirect
sed -i "/server_name localhost;/a$INSERT_LINE" $CONFIG_FILE

# start nginx after reloading config
service nginx start
