#!/usr/bin/env bash
# this script will be used as an ip set up script, works in docker
cp /etc/hosts ~/hosts.new
echo '127.0.0.2 localhost' >> ~/hosts.new
echo '8.8.8.8 facebook' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
